{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_list_valid_user[Admin-admin1230]", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_list_valid_user[Admin-admin1231]", "rerun": "0"}}, "suite_name": "OrangeHRM_Login_Test.py"}, "1": {"suite_name": "Test_Google.py", "tests": {"0": {"status": "ERROR", "message": "file C:\\Users\\adixit\\PycharmProjects\\Selenium_Demo\\PyTest_UI_Test\\Test_Google.py, line 10\n  def test_open_google_url(self):\nE       fixture 'self' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, driver_init, extra, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\adixit\\PycharmProjects\\Selenium_Demo\\PyTest_UI_Test\\Test_Google.py:10\n", "test_name": "test_open_google_url", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}}}}, "date": "May 30, 2021", "start_time": 1622385141.4659193, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "2", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}